

interface StyleBase {

    'initial': string;
    'inherit': string;
    'unset': string;
    null: null
}


interface StyleDisplay extends StyleBase {
    "flex": "flex";
    'block': string;
    'inline-block': string;
    'inline': string;
    'table': string;
    '-webkit-box': string;
    '-webkit-inline-box': string;
    'contents': string;
    'flow-root': string;
    'grid': string;
    'inline-flex': string;
    'inline-grid': string;
    'inline-table': string;
    'list-item': string;
    'none': string;
    'table-caption': string;
    'talbe-cell': string;
    'table-column': string;
    'table-colum-group': string;
    'table-footer-group': string;
    'table-header-group': string;
    'table-row': string;
    'table-row-group': string;
}


interface StyleFlexDirection extends StyleBase {
    'column': string;
    'column-reverse': string;
    'row': string;
    'row-reverse': string;
}

interface StyleAlignItems extends StyleBase {
    'baseline': string;
    'center': string;
    'end': string;
    'flex-end': string;
    'flex-start': string;
    'left': string;
    'normal': string;
    'right': string;
    'safe': string;
    'self-end': string;
    'self-start': string;
    'start': string;
    'stretch': string;
    'unsafe': string;
}
interface StyleJustifyContent extends StyleAlignItems {
    'space-around': string;
    'space-between': string;
    'space-evenly': string;
}

interface StylePosition extends StyleBase {
    'absolute': string;
    'fixed': string;
    'relative': string;
    'static': string;
    'sticky': string;
}

interface StyleFloat extends StyleBase {
    "left": string;
    "right": string;
    "none": string;
}
interface StyleWordBreak extends StyleBase {
    /**强制换行 */
    'break-all': string;
    'break-word': string;
    'keep-all': string;
    'normal': string;
}

interface StyleWhiteSpace extends StyleBase {

    'normal': string;
    'nowrap': string;
    'pre': string;
    'pre-line': string;
    'pre-wrap': string;

}

interface StyleBoxSizing extends StyleBase {
    'content-box': string;
    'border-box': string;
}

interface StyleTextAlign extends StyleBase {
    '-webkit-auto': string;
    '-webkit-center': string;
    '-webkit-left': string;
    '-webkit-match-parent': string;
    '-webkit-right': string;
    'center': string;
    'end': string;
    'justify': string;
    'left': string;
    'right': string;
    'start': string;
}

interface StyleTextOverflow extends StyleBase {
    'ellipsis': string;
    'clip': string;
}

interface StyleInterface {

    display?: keyof StyleDisplay;
    flexDirection?: keyof StyleFlexDirection;
    justifyContent?: keyof StyleJustifyContent;
    position?: keyof StylePosition;
    cssFloat?: keyof StyleFloat;
    wordBreak?: keyof StyleWordBreak;
    whiteSpace?: keyof StyleWhiteSpace;
    boxSizing?: keyof StyleBoxSizing;
    textAlign?: keyof StyleTextAlign;
    TextOverflow?: keyof StyleTextOverflow;

    alignContent?: keyof StyleJustifyContent;
    alignItems?: keyof StyleJustifyContent;
    alignSelf?: keyof StyleAlignItems;
    alignmentBaseline?: keyof StyleBase
    animation?: keyof StyleBase | 'auto' | 'none';
    animationDelay?: string | number | null;
    animationDirection?: string | number | null;
    animationDuration?: string | number | null;
    animationFillMode?: string | number | null;
    animationIterationCount?: string | number | null;
    animationName?: string | number | null;
    animationPlayState?: string | number | null;
    animationTimingFunction?: string | number | null;
    backfaceVisibility?: string | number | null;
    background?: string | number | null;
    backgroundAttachment?: string | number | null;
    backgroundClip?: string | number | null;
    backgroundColor?: string | number | null;
    backgroundImage?: string | number | null;
    backgroundOrigin?: string | number | null;
    backgroundPosition?: string | number | null;
    backgroundPositionX?: string | number | null;
    backgroundPositionY?: string | number | null;
    backgroundRepeat?: string | number | null;
    backgroundSize?: string | number | null;
    baselineShift?: string | number | null;
    border?: string | number | null;
    borderBottom?: string | number | null;
    borderBottomColor?: string | number | null;
    borderBottomLeftRadius?: string | number | null;
    borderBottomRightRadius?: string | number | null;
    borderBottomStyle?: string | number | null;
    borderBottomWidth?: string | number | null;
    borderCollapse?: string | number | null;
    borderColor?: string | number | null;
    borderImage?: string | number | null;
    borderImageOutset?: string | number | null;
    borderImageRepeat?: string | number | null;
    borderImageSlice?: string | number | null;
    borderImageSource?: string | number | null;
    borderImageWidth?: string | number | null;
    borderLeft?: string | number | null;
    borderLeftColor?: string | number | null;
    borderLeftStyle?: string | number | null;
    borderLeftWidth?: string | number | null;
    borderRadius?: string | number | null;
    borderRight?: string | number | null;
    borderRightColor?: string | number | null;
    borderRightStyle?: string | number | null;
    borderRightWidth?: string | number | null;
    borderSpacing?: string | number | null;
    borderStyle?: string | number | null;
    borderTop?: string | number | null;
    borderTopColor?: string | number | null;
    borderTopLeftRadius?: string | number | null;
    borderTopRightRadius?: string | number | null;
    borderTopStyle?: string | number | null;
    borderTopWidth?: string | number | null;
    borderWidth?: string | number | null;
    bottom?: string | number | null;
    boxShadow?: string | number | null;
    breakAfter?: string | number | null;
    breakBefore?: string | number | null;
    breakInside?: string | number | null;
    captionSide?: string | number | null;
    clear?: string | number | null;
    clip?: string | number | null;
    clipPath?: string | number | null;
    clipRule?: string | number | null;
    color?: string | number | null;
    colorInterpolationFilters?: string | number | null;
    columnCount?: any;
    columnFill?: string | number | null;
    columnGap?: any;
    columnRule?: string | number | null;
    columnRuleColor?: any;
    columnRuleStyle?: string | number | null;
    columnRuleWidth?: any;
    columnSpan?: string | number | null;
    columnWidth?: any;
    columns?: string | number | null;
    content?: string | number | null;
    counterIncrement?: string | number | null;
    counterReset?: string | number | null;
    cssText?: string;
    cursor?: string | number | null;
    direction?: string | number | null;
    dominantBaseline?: string | number | null;
    emptyCells?: string | number | null;
    enableBackground?: string | number | null;
    fill?: string | number | null;
    fillOpacity?: string | number | null;
    fillRule?: string | number | null;
    filter?: string | number | null;
    flex?: string | number | null;
    flexBasis?: string | number | null;
    flexFlow?: string | number | null;
    flexGrow?: string | number | null;
    flexShrink?: string | number | null;
    flexWrap?: string | number | null;
    floodColor?: string | number | null;
    floodOpacity?: string | number | null;
    font?: string | number | null;
    fontFamily?: string | number | null;
    fontFeatureSettings?: string | number | null;
    fontSize?: string | number | null;
    fontSizeAdjust?: string | number | null;
    fontStretch?: string | number | null;
    fontStyle?: string | number | null;
    fontVariant?: string | number | null;
    fontWeight?: string | number | null;
    gap?: string | number | null;
    glyphOrientationHorizontal?: string | number | null;
    glyphOrientationVertical?: string | number | null;
    grid?: string | number | null;
    gridArea?: string | number | null;
    gridAutoColumns?: string | number | null;
    gridAutoFlow?: string | number | null;
    gridAutoRows?: string | number | null;
    gridColumn?: string | number | null;
    gridColumnEnd?: string | number | null;
    gridColumnGap?: string | number | null;
    gridColumnStart?: string | number | null;
    gridGap?: string | number | null;
    gridRow?: string | number | null;
    gridRowEnd?: string | number | null;
    gridRowGap?: string | number | null;
    gridRowStart?: string | number | null;
    gridTemplate?: string | number | null;
    gridTemplateAreas?: string | number | null;
    gridTemplateColumns?: string | number | null;
    gridTemplateRows?: string | number | null;
    height?: string | number | null;
    imeMode?: string | number | null;
    justifyItems?: string | number | null;
    justifySelf?: string | number | null;
    kerning?: string | number | null;
    layoutGrid?: string | number | null;
    layoutGridChar?: string | number | null;
    layoutGridLine?: string | number | null;
    layoutGridMode?: string | number | null;
    layoutGridType?: string | number | null;
    left?: string | number | null;
    letterSpacing?: string | number | null;
    lightingColor?: string | number | null;
    lineBreak?: string | number | null;
    lineHeight?: string | number | null;
    listStyle?: string | number | null;
    listStyleImage?: string | number | null;
    listStylePosition?: string | number | null;
    listStyleType?: string | number | null;
    margin?: string | number | null;
    marginBottom?: string | number | null;
    marginLeft?: string | number | null;
    marginRight?: string | number | null;
    marginTop?: string | number | null;
    marker?: string | number | null;
    markerEnd?: string | number | null;
    markerMid?: string | number | null;
    markerStart?: string | number | null;
    mask?: string | number | null;
    maskImage?: string | number | null;
    maxHeight?: string | number | null;
    maxWidth?: string | number | null;
    minHeight?: string | number | null;
    minWidth?: string | number | null;
    msContentZoomChaining?: string | number | null;
    msContentZoomLimit?: string | number | null;
    msContentZoomLimitMax?: any;
    msContentZoomLimitMin?: any;
    msContentZoomSnap?: string | number | null;
    msContentZoomSnapPoints?: string | number | null;
    msContentZoomSnapType?: string | number | null;
    msContentZooming?: string | number | null;
    msFlowFrom?: string | number | null;
    msFlowInto?: string | number | null;
    msFontFeatureSettings?: string | number | null;
    msGridColumn?: any;
    msGridColumnAlign?: string | number | null;
    msGridColumnSpan?: any;
    msGridColumns?: string | number | null;
    msGridRow?: any;
    msGridRowAlign?: string | number | null;
    msGridRowSpan?: any;
    msGridRows?: string | number | null;
    msHighContrastAdjust?: string | number | null;
    msHyphenateLimitChars?: string | number | null;
    msHyphenateLimitLines?: any;
    msHyphenateLimitZone?: any;
    msHyphens?: string | number | null;
    msImeAlign?: string | number | null;
    msOverflowStyle?: string | number | null;
    msScrollChaining?: string | number | null;
    msScrollLimit?: string | number | null;
    msScrollLimitXMax?: any;
    msScrollLimitXMin?: any;
    msScrollLimitYMax?: any;
    msScrollLimitYMin?: any;
    msScrollRails?: string | number | null;
    msScrollSnapPointsX?: string | number | null;
    msScrollSnapPointsY?: string | number | null;
    msScrollSnapType?: string | number | null;
    msScrollSnapX?: string | number | null;
    msScrollSnapY?: string | number | null;
    msScrollTranslation?: string | number | null;
    msTextCombineHorizontal?: string | number | null;
    msTextSizeAdjust?: any;
    msTouchAction?: string | number | null;
    msTouchSelect?: string | number | null;
    msUserSelect?: string | number | null;
    msWrapFlow?: string;
    msWrapMargin?: any;
    msWrapThrough?: string;
    objectFit?: string | number | null;
    objectPosition?: string | number | null;
    opacity?: string | number | null;
    order?: string | number | null;
    orphans?: string | number | null;
    outline?: string | number | null;
    outlineColor?: string | number | null;
    outlineOffset?: string | number | null;
    outlineStyle?: string | number | null;
    outlineWidth?: string | number | null;
    overflow?: string | number | null;
    overflowX?: string | number | null;
    overflowY?: string | number | null;
    padding?: string | number | null;
    paddingBottom?: string | number | null;
    paddingLeft?: string | number | null;
    paddingRight?: string | number | null;
    paddingTop?: string | number | null;
    pageBreakAfter?: string | number | null;
    pageBreakBefore?: string | number | null;
    pageBreakInside?: string | number | null;
    penAction?: string | number | null;
    perspective?: string | number | null;
    perspectiveOrigin?: string | number | null;
    pointerEvents?: string | number | null;
    quotes?: string | number | null;
    resize?: string | number | null;
    right?: string | number | null;
    rotate?: string | number | null;
    rowGap?: string | number | null;
    rubyAlign?: string | number | null;
    rubyOverhang?: string | number | null;
    rubyPosition?: string | number | null;
    scale?: string | number | null;
    stopColor?: string | number | null;
    stopOpacity?: string | number | null;
    stroke?: string | number | null;
    strokeDasharray?: string | number | null;
    strokeDashoffset?: string | number | null;
    strokeLinecap?: string | number | null;
    strokeLinejoin?: string | number | null;
    strokeMiterlimit?: string | number | null;
    strokeOpacity?: string | number | null;
    strokeWidth?: string | number | null;
    tableLayout?: string | number | null;
    textAlignLast?: string | number | null;
    textAnchor?: string | number | null;
    textCombineUpright?: string | number | null;
    textDecoration?: string | number | null;
    textIndent?: string | number | null;
    textJustify?: string | number | null;
    textKashida?: string | number | null;
    textKashidaSpace?: string | number | null;
    textOverflow?: string | number | null;
    textShadow?: string | number | null;
    textTransform?: string | number | null;
    textUnderlinePosition?: string | number | null;
    top?: string | number | null;
    touchAction?: string | number | null;
    transform?: string | number | null;
    transformOrigin?: string | number | null;
    transformStyle?: string | number | null;
    transition?: string | number | null;
    transitionDelay?: string | number | null;
    transitionDuration?: string | number | null;
    transitionProperty?: string | number | null;
    transitionTimingFunction?: string | number | null;
    translate?: string | number | null;
    unicodeBidi?: string | number | null;
    userSelect?: string | number | null;
    verticalAlign?: string | number | null;
    visibility?: string | number | null;
    webkitAlignContent?: string | number | null;
    webkitAlignItems?: string | number | null;
    webkitAlignSelf?: string | number | null;
    webkitAnimation?: string | number | null;
    webkitAnimationDelay?: string | number | null;
    webkitAnimationDirection?: string | number | null;
    webkitAnimationDuration?: string | number | null;
    webkitAnimationFillMode?: string | number | null;
    webkitAnimationIterationCount?: string | number | null;
    webkitAnimationName?: string | number | null;
    webkitAnimationPlayState?: string | number | null;
    webkitAnimationTimingFunction?: string | number | null;
    webkitAppearance?: string | number | null;
    webkitBackfaceVisibility?: string | number | null;
    webkitBackgroundClip?: string | number | null;
    webkitBackgroundOrigin?: string | number | null;
    webkitBackgroundSize?: string | number | null;
    webkitBorderBottomLeftRadius?: string | number | null;
    webkitBorderBottomRightRadius?: string | number | null;
    webkitBorderImage?: string | number | null;
    webkitBorderRadius?: string | number | null;
    webkitBorderTopLeftRadius?: string | number | null;
    webkitBorderTopRightRadius?: string | number | null;
    webkitBoxAlign?: string | number | null;
    webkitBoxDirection?: string | number | null;
    webkitBoxFlex?: string | number | null;
    webkitBoxOrdinalGroup?: string | number | null;
    webkitBoxOrient?: string | number | null;
    webkitBoxPack?: string | number | null;
    webkitBoxSizing?: string | number | null;
    webkitColumnBreakAfter?: string | number | null;
    webkitColumnBreakBefore?: string | number | null;
    webkitColumnBreakInside?: string | number | null;
    webkitColumnCount?: any;
    webkitColumnGap?: any;
    webkitColumnRule?: string | number | null;
    webkitColumnRuleColor?: any;
    webkitColumnRuleStyle?: string | number | null;
    webkitColumnRuleWidth?: any;
    webkitColumnSpan?: string | number | null;
    webkitColumnWidth?: any;
    webkitColumns?: string | number | null;
    webkitFilter?: string | number | null;
    webkitFlex?: string | number | null;
    webkitFlexBasis?: string | number | null;
    webkitFlexDirection?: string | number | null;
    webkitFlexFlow?: string | number | null;
    webkitFlexGrow?: string | number | null;
    webkitFlexShrink?: string | number | null;
    webkitFlexWrap?: string | number | null;
    webkitJustifyContent?: string | number | null;
    webkitOrder?: string | number | null;
    webkitPerspective?: string | number | null;
    webkitPerspectiveOrigin?: string | number | null;
    webkitTapHighlightColor?: string | number | null;
    webkitTextFillColor?: string | number | null;
    webkitTextSizeAdjust?: any;
    webkitTextStroke?: string | number | null;
    webkitTextStrokeColor?: string | number | null;
    webkitTextStrokeWidth?: string | number | null;
    webkitTransform?: string | number | null;
    webkitTransformOrigin?: string | number | null;
    webkitTransformStyle?: string | number | null;
    webkitTransition?: string | number | null;
    webkitTransitionDelay?: string | number | null;
    webkitTransitionDuration?: string | number | null;
    webkitTransitionProperty?: string | number | null;
    webkitTransitionTimingFunction?: string | number | null;
    webkitUserModify?: string | number | null;
    webkitUserSelect?: string | number | null;
    webkitWritingMode?: string | number | null;
    widows?: string | number | null;
    width?: string | number | null;
    wordSpacing?: string | number | null;
    wordWrap?: string | number | null;
    writingMode?: string | number | null;
    zIndex?: string | number | null;
    zoom?: string | number | null;
}


interface StyleStringInterface {

    'display'?: keyof StyleDisplay;
    'flex-direction'?: keyof StyleFlexDirection;
    'justify-content'?: keyof StyleJustifyContent;
    'position'?: keyof StylePosition;
    'css-float'?: keyof StyleFloat;
    'word-break'?: keyof StyleWordBreak;
    'white-space'?: keyof StyleWhiteSpace;
    'box-sizing'?: keyof StyleBoxSizing;
    'text-align'?: keyof StyleTextAlign;
    'text-overflow'?: keyof StyleTextOverflow;

    'align-content'?: keyof StyleJustifyContent;
    'align-items'?: keyof StyleJustifyContent;
    'align-self'?: keyof StyleAlignItems;
    'alignment-baseline'?: keyof StyleBase
    'animation'?: keyof StyleBase | 'auto' | 'none';
    'animation-delay'?: string | number | null;
    'animation-direction'?: string | number | null;
    'animation-duration'?: string | number | null;
    'animation-fill-mode'?: string | number | null;
    'animation-iteration-count'?: string | number | null;
    'animation-name'?: string | number | null;
    'animation-play-state'?: string | number | null;
    'animation-timing-function'?: string | number | null;
    'backface-visibility'?: string | number | null;
    'background'?: string | number | null;
    'background-attachment'?: string | number | null;
    'background-clip'?: string | number | null;
    'background-color'?: string | number | null;
    'background-image'?: string | number | null;
    'background-origin'?: string | number | null;
    'background-position'?: string | number | null;
    'background-position-x'?: string | number | null;
    'background-position-y'?: string | number | null;
    'background-repeat'?: string | number | null;
    'background-size'?: string | number | null;
    'baseline-shift'?: string | number | null;
    'border'?: string | number | null;
    'border-bottom'?: string | number | null;
    'border-bottom-color'?: string | number | null;
    'border-bottom-left-radius'?: string | number | null;
    'border-bottom-right-radius'?: string | number | null;
    'border-bottom-style'?: string | number | null;
    'border-bottom-width'?: string | number | null;
    'border-collapse'?: string | number | null;
    'border-color'?: string | number | null;
    'border-image'?: string | number | null;
    'border-image-outset'?: string | number | null;
    'border-image-repeat'?: string | number | null;
    'border-image-slice'?: string | number | null;
    'border-image-source'?: string | number | null;
    'border-image-width'?: string | number | null;
    'border-left'?: string | number | null;
    'border-left-color'?: string | number | null;
    'border-left-style'?: string | number | null;
    'border-left-width'?: string | number | null;
    'border-radius'?: string | number | null;
    'border-right'?: string | number | null;
    'border-right-color'?: string | number | null;
    'border-right-style'?: string | number | null;
    'border-right-width'?: string | number | null;
    'border-spacing'?: string | number | null;
    'border-style'?: string | number | null;
    'border-top'?: string | number | null;
    'border-top-color'?: string | number | null;
    'border-top-left-radius'?: string | number | null;
    'border-top-right-radius'?: string | number | null;
    'border-top-style'?: string | number | null;
    'border-top-width'?: string | number | null;
    'border-width'?: string | number | null;
    'bottom'?: string | number | null;
    'box-shadow'?: string | number | null;
    'break-after'?: string | number | null;
    'break-before'?: string | number | null;
    'break-inside'?: string | number | null;
    'caption-side'?: string | number | null;
    'clear'?: string | number | null;
    'clip'?: string | number | null;
    'clip-path'?: string | number | null;
    'clip-rule'?: string | number | null;
    'color'?: string | number | null;
    'color-interpolation-filters'?: string | number | null;
    'column-count'?: any;
    'column-fill'?: string | number | null;
    'column-gap'?: any;
    'column-rule'?: string | number | null;
    'column-rule-color'?: any;
    'column-rule-style'?: string | number | null;
    'column-rule-width'?: any;
    'column-span'?: string | number | null;
    'column-width'?: any;
    'columns'?: string | number | null;
    'content'?: string | number | null;
    'counter-increment'?: string | number | null;
    'counter-reset'?: string | number | null;
    'css-text'?: string;
    'cursor'?: string | number | null;
    'direction'?: string | number | null;
    'dominant-baseline'?: string | number | null;
    'empty-cells'?: string | number | null;
    'enable-background'?: string | number | null;
    'fill'?: string | number | null;
    'fill-opacity'?: string | number | null;
    'fill-rule'?: string | number | null;
    'filter'?: string | number | null;
    'flex'?: string | number | null;
    'flex-basis'?: string | number | null;
    'flex-flow'?: string | number | null;
    'flex-grow'?: string | number | null;
    'flex-shrink'?: string | number | null;
    'flex-wrap'?: string | number | null;
    'flood-color'?: string | number | null;
    'flood-opacity'?: string | number | null;
    'font'?: string | number | null;
    'font-family'?: string | number | null;
    'font-feature-settings'?: string | number | null;
    'font-size'?: string | number | null;
    'font-size-adjust'?: string | number | null;
    'font-stretch'?: string | number | null;
    'font-style'?: string | number | null;
    'font-variant'?: string | number | null;
    'font-weight'?: string | number | null;
    'gap'?: string | number | null;
    'glyph-orientation-horizontal'?: string | number | null;
    'glyph-orientation-vertical'?: string | number | null;
    'grid'?: string | number | null;
    'grid-area'?: string | number | null;
    'grid-auto-columns'?: string | number | null;
    'grid-auto-flow'?: string | number | null;
    'grid-auto-rows'?: string | number | null;
    'grid-column'?: string | number | null;
    'grid-column-end'?: string | number | null;
    'grid-column-gap'?: string | number | null;
    'grid-column-start'?: string | number | null;
    'grid-gap'?: string | number | null;
    'grid-row'?: string | number | null;
    'grid-row-end'?: string | number | null;
    'grid-row-gap'?: string | number | null;
    'grid-row-start'?: string | number | null;
    'grid-template'?: string | number | null;
    'grid-template-areas'?: string | number | null;
    'grid-template-columns'?: string | number | null;
    'grid-template-rows'?: string | number | null;
    'height'?: string | number | null;
    'ime-mode'?: string | number | null;
    'justify-items'?: string | number | null;
    'justify-self'?: string | number | null;
    'kerning'?: string | number | null;
    'layout-grid'?: string | number | null;
    'layout-grid-char'?: string | number | null;
    'layout-grid-line'?: string | number | null;
    'layout-grid-mode'?: string | number | null;
    'layout-grid-type'?: string | number | null;
    'left'?: string | number | null;
    'letter-spacing'?: string | number | null;
    'lighting-color'?: string | number | null;
    'line-break'?: string | number | null;
    'line-height'?: string | number | null;
    'list-style'?: string | number | null;
    'list-style-image'?: string | number | null;
    'list-style-position'?: string | number | null;
    'list-style-type'?: string | number | null;
    'margin'?: string | number | null;
    'margin-bottom'?: string | number | null;
    'margin-left'?: string | number | null;
    'margin-right'?: string | number | null;
    'margin-top'?: string | number | null;
    'marker'?: string | number | null;
    'marker-end'?: string | number | null;
    'marker-mid'?: string | number | null;
    'marker-start'?: string | number | null;
    'mask'?: string | number | null;
    'mask-image'?: string | number | null;
    'max-height'?: string | number | null;
    'max-width'?: string | number | null;
    'min-height'?: string | number | null;
    'min-width'?: string | number | null;
    '-ms-content-zoom-chaining'?: string | number | null;
    '-ms-content-zoom-limit'?: string | number | null;
    '-ms-content-zoom-limit-max'?: any;
    '-ms-content-zoom-limit-min'?: any;
    '-ms-content-zoom-snap'?: string | number | null;
    '-ms-content-zoom-snap-points'?: string | number | null;
    '-ms-content-zoom-snap-type'?: string | number | null;
    '-ms-content-zooming'?: string | number | null;
    '-ms-flow-from'?: string | number | null;
    '-ms-flow-into'?: string | number | null;
    '-ms-font-feature-settings'?: string | number | null;
    '-ms-grid-column'?: any;
    '-ms-grid-column-align'?: string | number | null;
    '-ms-grid-column-span'?: any;
    '-ms-grid-columns'?: string | number | null;
    '-ms-grid-row'?: any;
    '-ms-grid-row-align'?: string | number | null;
    '-ms-grid-row-span'?: any;
    '-ms-grid-rows'?: string | number | null;
    '-ms-high-contrast-adjust'?: string | number | null;
    '-ms-hyphenate-limit-chars'?: string | number | null;
    '-ms-hyphenate-limit-lines'?: any;
    '-ms-hyphenate-limit-zone'?: any;
    '-ms-hyphens'?: string | number | null;
    '-ms-ime-align'?: string | number | null;
    '-ms-overflow-style'?: string | number | null;
    '-ms-scroll-chaining'?: string | number | null;
    '-ms-scroll-limit'?: string | number | null;
    '-ms-scroll-limit-x-max'?: any;
    '-ms-scroll-limit-x-min'?: any;
    '-ms-scroll-limit-y-max'?: any;
    '-ms-scroll-limit-y-min'?: any;
    '-ms-scroll-rails'?: string | number | null;
    '-ms-scroll-snap-points-x'?: string | number | null;
    '-ms-scroll-snap-points-y'?: string | number | null;
    '-ms-scroll-snap-type'?: string | number | null;
    '-ms-scroll-snap-x'?: string | number | null;
    '-ms-scroll-snap-y'?: string | number | null;
    '-ms-scroll-translation'?: string | number | null;
    '-ms-text-combine-horizontal'?: string | number | null;
    '-ms-text-size-adjust'?: any;
    '-ms-touch-action'?: string | number | null;
    '-ms-touch-select'?: string | number | null;
    '-ms-user-select'?: string | number | null;
    '-ms-wrap-flow'?: string;
    '-ms-wrap-margin'?: any;
    '-ms-wrap-through'?: string;
    'object-fit'?: string | number | null;
    'object-position'?: string | number | null;
    'opacity'?: string | number | null;
    'order'?: string | number | null;
    'orphans'?: string | number | null;
    'outline'?: string | number | null;
    'outline-color'?: string | number | null;
    'outline-offset'?: string | number | null;
    'outline-style'?: string | number | null;
    'outline-width'?: string | number | null;
    'overflow'?: string | number | null;
    'overflow-x'?: string | number | null;
    'overflow-y'?: string | number | null;
    'padding'?: string | number | null;
    'padding-bottom'?: string | number | null;
    'padding-left'?: string | number | null;
    'padding-right'?: string | number | null;
    'padding-top'?: string | number | null;
    'page-break-after'?: string | number | null;
    'page-break-before'?: string | number | null;
    'page-break-inside'?: string | number | null;
    'pen-action'?: string | number | null;
    'perspective'?: string | number | null;
    'perspective-origin'?: string | number | null;
    'pointer-events'?: string | number | null;
    'quotes'?: string | number | null;
    'resize'?: string | number | null;
    'right'?: string | number | null;
    'rotate'?: string | number | null;
    'row-gap'?: string | number | null;
    'ruby-align'?: string | number | null;
    'ruby-overhang'?: string | number | null;
    'ruby-position'?: string | number | null;
    'scale'?: string | number | null;
    'stop-color'?: string | number | null;
    'stop-opacity'?: string | number | null;
    'stroke'?: string | number | null;
    'stroke-dasharray'?: string | number | null;
    'stroke-dashoffset'?: string | number | null;
    'stroke-linecap'?: string | number | null;
    'stroke-linejoin'?: string | number | null;
    'stroke-miterlimit'?: string | number | null;
    'stroke-opacity'?: string | number | null;
    'stroke-width'?: string | number | null;
    'table-layout'?: string | number | null;
    'text-align-last'?: string | number | null;
    'text-anchor'?: string | number | null;
    'text-combine-upright'?: string | number | null;
    'text-decoration'?: string | number | null;
    'text-indent'?: string | number | null;
    'text-justify'?: string | number | null;
    'text-kashida'?: string | number | null;
    'text-kashida-space'?: string | number | null;
    'text-shadow'?: string | number | null;
    'text-transform'?: string | number | null;
    'text-underline-position'?: string | number | null;
    'top'?: string | number | null;
    'touch-action'?: string | number | null;
    'transform'?: string | number | null;
    'transform-origin'?: string | number | null;
    'transform-style'?: string | number | null;
    'transition'?: string | number | null;
    'transition-delay'?: string | number | null;
    'transition-duration'?: string | number | null;
    'transition-property'?: string | number | null;
    'transition-timing-function'?: string | number | null;
    'translate'?: string | number | null;
    'unicode-bidi'?: string | number | null;
    'user-select'?: string | number | null;
    'vertical-align'?: string | number | null;
    'visibility'?: string | number | null;
    '-webkit-align-content'?: string | number | null;
    '-webkit-align-items'?: string | number | null;
    '-webkit-align-self'?: string | number | null;
    '-webkit-animation'?: string | number | null;
    '-webkit-animation-delay'?: string | number | null;
    '-webkit-animation-direction'?: string | number | null;
    '-webkit-animation-duration'?: string | number | null;
    '-webkit-animation-fill-mode'?: string | number | null;
    '-webkit-animation-iteration-count'?: string | number | null;
    '-webkit-animation-name'?: string | number | null;
    '-webkit-animation-play-state'?: string | number | null;
    '-webkit-animation-timing-function'?: string | number | null;
    '-webkit-appearance'?: string | number | null;
    '-webkit-backface-visibility'?: string | number | null;
    '-webkit-background-clip'?: string | number | null;
    '-webkit-background-origin'?: string | number | null;
    '-webkit-background-size'?: string | number | null;
    '-webkit-border-bottom-left-radius'?: string | number | null;
    '-webkit-border-bottom-right-radius'?: string | number | null;
    '-webkit-border-image'?: string | number | null;
    '-webkit-border-radius'?: string | number | null;
    '-webkit-border-top-left-radius'?: string | number | null;
    '-webkit-border-top-right-radius'?: string | number | null;
    '-webkit-box-align'?: string | number | null;
    '-webkit-box-direction'?: string | number | null;
    '-webkit-box-flex'?: string | number | null;
    '-webkit-box-ordinal-group'?: string | number | null;
    '-webkit-box-orient'?: string | number | null;
    '-webkit-box-pack'?: string | number | null;
    '-webkit-box-sizing'?: string | number | null;
    '-webkit-column-break-after'?: string | number | null;
    '-webkit-column-break-before'?: string | number | null;
    '-webkit-column-break-inside'?: string | number | null;
    '-webkit-column-count'?: any;
    '-webkit-column-gap'?: any;
    '-webkit-column-rule'?: string | number | null;
    '-webkit-column-rule-color'?: any;
    '-webkit-column-rule-style'?: string | number | null;
    '-webkit-column-rule-width'?: any;
    '-webkit-column-span'?: string | number | null;
    '-webkit-column-width'?: any;
    '-webkit-columns'?: string | number | null;
    '-webkit-filter'?: string | number | null;
    '-webkit-flex'?: string | number | null;
    '-webkit-flex-basis'?: string | number | null;
    '-webkit-flex-direction'?: string | number | null;
    '-webkit-flex-flow'?: string | number | null;
    '-webkit-flex-grow'?: string | number | null;
    '-webkit-flex-shrink'?: string | number | null;
    '-webkit-flex-wrap'?: string | number | null;
    '-webkit-justify-content'?: string | number | null;
    '-webkit-order'?: string | number | null;
    '-webkit-perspective'?: string | number | null;
    '-webkit-perspective-origin'?: string | number | null;
    '-webkit-tap-highlight-color'?: string | number | null;
    '-webkit-text-fill-color'?: string | number | null;
    '-webkit-text-size-adjust'?: any;
    '-webkit-text-stroke'?: string | number | null;
    '-webkit-text-stroke-color'?: string | number | null;
    '-webkit-text-stroke-width'?: string | number | null;
    '-webkit-transform'?: string | number | null;
    '-webkit-transform-origin'?: string | number | null;
    '-webkit-transform-style'?: string | number | null;
    '-webkit-transition'?: string | number | null;
    '-webkit-transition-delay'?: string | number | null;
    '-webkit-transition-duration'?: string | number | null;
    '-webkit-transition-property'?: string | number | null;
    '-webkit-transition-timing-function'?: string | number | null;
    '-webkit-user-modify'?: string | number | null;
    '-webkit-user-select'?: string | number | null;
    '-webkit-writing-mode'?: string | number | null;
    'widows'?: string | number | null;
    'width'?: string | number | null;
    'word-spacing'?: string | number | null;
    'word-wrap'?: string | number | null;
    'writing-mode'?: string | number | null;
    'z-index'?: string | number | null;
    'zoom'?: string | number | null;
}